apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: toolbox
  labels:
    app: toolbox
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      containers:
      - name: toolbox
        image: harbor.qyvideo.net/k8s/toolbox:0.1