apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  labels:
    name: blackbox-exporter
  annotations:
    prometheus.io/probe: "true"
  namespace: monitoring
spec:
  ports:
    - port: 9115
      targetPort: 9115
      protocol: TCP
  selector:
    app: blackbox-exporter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blackbox-exporter
  labels:
    app: blackbox-exporter
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
      - name: blackbox-exporter
        image: harbor.qyvideo.net/duanyifei-test/blackbox-exporter:v0.12.0
