---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: prometheus-node-exporter
  namespace: monitoring
  labels:
    app: prome-node-exporter
spec:
  template:
    metadata:
      name: prometheus-node-exporter
      labels:
        app: prome-node-exporter
    spec:
      containers:
      - image: harbor.qyvideo.net/kubernetes-monitor/node-exporter:v0.14.0
        name: prometheus-node-exporter
        ports:
        - name: prom-node-exp
          containerPort: 9100
          hostPort: 9100
      hostNetwork: true
      hostPID: true