groups:
- name: basic
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."

  - alert: port_success
    expr: probe_success < 1
    for: 1m
    annotations:
      summary: "Job: {{ $labels.job }}, Instance:{{ $labels.instance }}, service port down."

  - alert: basic_cpu_idle
    expr: avg(irate(node_cpu{mode="idle"}[5m]) * 100) by (job, instance) < 10
    for: 2m
    annotations:
      summary: "Job: {{ $labels.job }}, Instance:{{ $labels.instance }}, cpu剩余不足10%, current_value: {{ $value }}"

  - alert: basic_cpu_insufficiency
    expr: avg(irate(node_cpu{mode="idle"}[5m]) * 100) BY (instance, job) < 20 and avg(irate(node_cpu{mode="steal"}[5m]) * 100) BY (instance, job) > 10
    for: 2m
    annotations:
      summary: "Job: {{ $labels.job }}, Instance:{{ $labels.instance }} cpu抢占>10%,cpu剩余不足30%"

  - alert: basic_cpu_insufficiency
    expr: avg(irate(node_cpu{mode="idle"}[5m]) * 100) BY (instance, job) < 20 and avg(irate(node_cpu{mode="steal"}[5m]) * 100) BY (instance, job) > 10
    for: 2m
    annotations:
      summary: "Job: {{ $labels.job }}, Instance:{{ $labels.instance }}, cpu抢占>10%,cpu剩余不足30%, current_value: {{ $value }}"

  - alert: basic_iowait
    expr: avg(irate(node_cpu{mode="iowait"}[5m]) * 100) BY (instance, job) > 20
    for: 1m
    annotations:
      summary: "Job: {{ $labels.job }}, Instance:{{ $labels.instance }}, iowait率偏高, current_value: {{ $value }}"

  - alert: basic_mem_free
    expr: (node_memory_MemFree{service=""} + node_memory_Cached{service=""})
      / node_memory_MemTotal{service=""} * 100 < 10
    for: 1m
    annotations:
      summary: "空闲内存占比<10%  current_value: {{ $value }}%"

  - alert: basic_sys_disk_usage
    expr: node_filesystem_free{mountpoint="/"} / node_filesystem_size{mountpoint="/"}
      * 100 < 20
    for: 1m
    annotations:
      summary: "Job: {{ $labels.job }}, Instance:{{ $labels.instance }}, 系统盘剩余不足20%  current_value: {{ $value }}%"

  - alert: basic_data_disk_usage
    expr: node_filesystem_free{mountpoint=~"/data|/mnt"} / node_filesystem_size{mountpoint=~"/data|/mnt"}
      * 100 < 20
    for: 1m
    annotations:
      summary: "Job: {{ $labels.job }}, Instance:{{ $labels.instance }}, 数据盘剩余不足50%  current_value: {{ $value }}%"

#  - alert: sum_monitor_target
#    expr: count(count(node_cpu) by (instance)) < 100
#    for: 1m
#    labels:
#      severity: critical
#    annotations:
#      summary: "实例存活数<200"

  - alert: system_load5
    expr: node_load5 / count(count(node_cpu) without (mode)) without (cpu) > 2
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Job: {{ $labels.job }}, Instance:{{ $labels.instance }}, system load 过高  current_value: {{ $value }}"