apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
  labels:
    name: filebeat-config
data:
  filebeat.yml: |
    filebeat.prospectors:
    - type: log
      enabled: true
      paths:
        - /data/logs/*/*.log
        - /data/logs/*.log
      exclude_files: ['.supervisor.log$']
      ignore_older: 2h
      tail_files: true
    output.kafka:
      hosts: ["kmr-6b5b65e0-gn-0268aba9-master-1-001.ksc.com:6667", "kmr-6b5b65e0-gn-0268aba9-core-1-001.ksc.com:6667", "kmr-6b5b65e0-gn-0268aba9-core-1-002.ksc.com:6667"]
      topic: "kvision-log"
      worker: 3
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      hostAliases:
      - ip: "10.19.24.13"
        hostnames:
          - "kmr-6b5b65e0-gn-0268aba9-master-1-001.ksc.com"
      - ip: "10.19.24.14"
        hostnames:
          - "kmr-6b5b65e0-gn-0268aba9-core-1-001.ksc.com"
      - ip: "10.19.24.2"
        hostnames:
          - "kmr-6b5b65e0-gn-0268aba9-core-1-002.ksc.com"
      hostNetwork: true
      containers:
      - image: harbor.qyvideo.net/duanyifei-test/filebeat:6.1.1_v1
        name: filebeat
        volumeMounts:
          - name: filebeat-config
            mountPath: /usr/share/filebeat/filebeat.yml
            subPath: filebeat.yml
          - name: log-path
            mountPath: /data/logs
      volumes:
        - name: filebeat-config
          configMap:
            name: filebeat-config
        - name: log-path
          hostPath:
            path: /data/logs