apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-pv-NODE_HOSTNAME
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zk-storage
  local:
    path: /data/k8s/zookeeper
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - NODE_HOSTNAME
